### ISSUE TITLE
Public Beta Checklist

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#330]
This is a placeholder issue, for organising the tasks for the Public Beta launch of Ignition.

## TODO

- [x] Update branding to `Hardhat Ignition`
- [x] Update UI/UX
  * [x] Update the visualize report
  * [x] Update the cli UI
- [x] Analytics
- [x] https://github.com/NomicFoundation/ignition/issues/418
- [x] https://github.com/NomicFoundation/ignition/issues/413
- [x] https://github.com/NomicFoundation/ignition/issues/442
- [x] https://github.com/NomicFoundation/ignition/issues/411
- [x] https://github.com/NomicFoundation/ignition/issues/419
- [x] https://github.com/NomicFoundation/hardhat-ignition/issues/527
- [x] https://github.com/NomicFoundation/hardhat-ignition/issues/530
- [x] https://github.com/NomicFoundation/hardhat-ignition/issues/531
- [x] https://github.com/NomicFoundation/hardhat-ignition/issues/500
- [x] #532
- [x] #533
- [x] https://github.com/NomicFoundation/hardhat-ignition/issues/509
- [ ] Demo video
- [x] Announcement blogpost
- [x] Announcement tweet
