### ISSUE TITLE
Additional Validations

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#368]
We can improve the UX by adding the following:

## TODO

- [ ] send needs its data param to be undefined, we are not doing param checks
- [ ] Validate that args are passed and not an options object
- [ ] validate that parameters is structured by module Ids
- [ ] Add validation on contract to see if artifact was passed as second argument
