### ISSUE TITLE
Include .gitignore section in docs

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#446]
The deployments folder should likely be included in your project's repo, to allow for using the successfully deployed contracts.

This will vary project to project, but the docs should include a section on the trade-offs (repo bloat vs access to all the information).

## TODO

- [ ] Determine where to add the section
- [ ] Consider whether we are giving fine grained advice (consequences of leaving out the journal for instance)
- [ ] Add the section
