### ISSUE TITLE
Apply new styling based on figma

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#493]
See the figma doc for more details:

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/24030/58a5fcfc-aee4-4fc1-9294-f6433d9aa171)

## TODO

- [x] Rework futures list in to batches
- [x] Implement linking between futures in batches
- [ ] Implement highlighting of diagram on hover of future in batch
- [x] Rename section to Execution batches
- [ ] The summary should show the contract name being deployed, and an `x4` after it to indicate the number of instances
- [x] The tooltip should explain the concept of `futures`
- [x] The different batches buttons on the diagram, on hover of batch number should highlight in the mermaid diagram the futures that make up that batch.
