### ISSUE TITLE
Apply the cli UI tweaks

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#530]
Testing has shown a set of small changes that should be made to the UI. See the UI tweaks doc in notion for full details.

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/24030/0f7d29b3-e467-4b96-8156-5affa5453ea0)

![image](https://github.com/NomicFoundation/hardhat-ignition/assets/24030/be833696-c9ed-46ed-b3da-09feac7c8ad2)

## TODO

- [ ] remove separator lines
- [ ] update the main title
- [ ] update the Deploying subtitle
- [ ] Change the successfully executed future text
- [ ] Change the running future text
- [ ] change the successful deployment section subtitle
- [ ] add blankline to end of completed text
- [ ] Update the boldness of the titles and subtitles
- [ ] limit use of emoji, only illustration not content
