### ISSUE TITLE
Update readmes

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#533]
Update the readmes in the repository.

## TODO

- [x] Add a good [README.md](http://readme.md/) to the respository
- [x] Add a good [README.md](http://readme.md/) to hardhat-ignition as this is the main NPM entry point
- [x] Add a decent [README.md](http://readme.md/) to ignition-core (this is an internal package, less important)
- [x] Add the Ignition banner image to the root repo readme
