### ISSUE TITLE
Give visual indication that there was a gas bump

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#587]
This will need some design work around the UI. Currently we give no indication that we are bumping fees, the user doesn't see any changes or updates happening.

Maybe something link:

```
Batch #26 

- xxx bumping gas fee (n/4)

## TODO

- [ ] Enhance deployment start with passing the config (no_of_confirmations)
- [ ] Enhance the UI state from the bump event
- [ ] Come up with a basic UI that displays a bump against the future
- [ ] Iterate on feedback to basic UI
