### ISSUE TITLE
Create migration guide from `hardhat-deploy` to Hardhat Ignition

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#590]
This will be a blog post that becomes a guide in Hardhat Ignition's docs.

## TODO

- [ ] Create an blogpost outline
- [ ] Create a feature comparison list
- [ ] Write up blogpost
- [ ] Convert to docs guide
