### ISSUE TITLE
include HH Ignition in HH ethers toolbox

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#596]
To allow users to leverage HH Ignition in new projects we want to include HH Ignition in the toolbox. Initially this will be the ethers toolbox, but the viem toolbox should follow as soon as we have viem support.

## TODO

- [ ] Update HH docs to assume HH Ignition and to sign post it
- [ ] Update HH sample projects
- [ ] Update HH init - include the ignition folders
