### ISSUE TITLE
Update HH docs to reflect move to toolbox

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#613]
The Hardhat docs needed to be checked and updated, referring to Ignition as the suggested method of deploying contracts.

## TODO

- [ ] Update the tutorial
  - [ ] deploying to external networks
  - [ ] consider if updating the tests makes sense
- [ ] Update deploying your contracts
- [ ] Consider updating the verification section
