### ISSUE TITLE
Determine duplication and potential for sharing up code

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#616]
Based on the viem plugin PR  https://github.com/NomicFoundation/hardhat-ignition/pull/612, determine the extent to which a shared package would minimize duplication and how much DRYing up is possible between two HH plugin packages.

## TODO

- [ ] Can tasks be shared up?
- [ ] Can the UI be moved into a shared package?
- [ ] How much of ignition helper can be extracted and shared?
- [ ] Where do the integration tests go?
