### ISSUE TITLE
`create2` execution strategy

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#661]
We have a POC of using createX to implement a `create2` execution strategy. We want to work this up to a full implementation that we can release. You can find the PR here: https://github.com/NomicFoundation/hardhat-ignition/pull/626

## TODO

- [x] Rebase with development
- [x] Update CreateX to `v0.1.0`
  - [x] In strategy update the list of existing deployed addresses to match: https://createx.rocks/deployments. If the network is not in the list, call `eth_getCode` at the create2 factory address `0xba5Ed099633D3B313e4D5F7bdc1305d3c28ba5Ed` to see if someone else has deployed it.
  - [x] In strategy init leverage the signed transactions outlined here: https://github.com/pcaversaccio/createx#new-deployments, to support creation of a factory in local nodes. If the factory is not present and it is not a 31337 chainId (i.e. a HH node) throw - we can deal with deploying a factory against a real network as a separate issue.
- [x] Update the api on the deploy function to be an enumeration that can have two values: `basic` | `create2`. If no strategy is given default to `basic`.
- [x] Update the UI to show the strategy, the suggestion is everywhere we currently show `Deploying [xxx]` we should show the strategy (and that it is a strategy). If other changes are needed make a call. The UI tweaks doc is likely useful for considering the different cases: https://www.notion.so/nomicfoundation/UI-tweaks-4197056e017e43239550c582f9b962cb?pvs=4

## Test Suite

Maybe an approach to testing here is to add a new section under the `hardat-plugin` package integration tests.

Those tests should iterate between the two strategies: `basic` and `create2` for a core set of tests:

1. Deploy a contract
2. Deploy multiple contracts
3. Make a call against a contract
4. Read an event from a constructor
5. Read an event from a call

The goal here is to show up a problem with a strategy where we switch from one strategy to another (e.g. calls still work even though we are mainly about contract deploys in create2), and allow us to support an increasing number of strategies.

There should also be a section of integration tests just for create2 testing:

1. Deploy with an existing create2 contract based on the known list (chainId hackery for the win)
2. Deploy with an existing create2 not on the list
3. Deploy without a create2 to 31337
4. Deploy without a create2 to non-31337 throws

**Comment by lastperson** [comment]
Hello. While the CREATE2 could be usable for independent contracts, it does not allow deployments to the same address if you use different constructor parameters (for immutable variables for instance).
CreateX conveniently provides a CREATE3 functionality, that lets you deploy to a deterministic address independent from the actual bytecode. This would probably be more useful for Hardhat users.
Do you think it would be better to add create3 strategy, or modify the create2 one to actually work as create3?

**Comment by kanej** [comment]
> Hello. While the CREATE2 could be usable for independent contracts, it does not allow deployments to the same address if you use different constructor parameters (for immutable variables for instance). CreateX conveniently provides a CREATE3 functionality, that lets you deploy to a deterministic address independent from the actual bytecode. This would probably be more useful for Hardhat users. Do you think it would be better to add create3 strategy, or modify the create2 one to actually work as create3?

Hey @lastperson, `create3` support is a great suggestion. I have opened an issue for it here: https://github.com/NomicFoundation/hardhat-ignition/issues/726, so others can weigh in/up vote.
