### ISSUE TITLE
HH Toolbox inclusion

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#669]
Ignition is to be included in both the standard HH toolbox and the viem toolbox.

This issue is to track the external repos that will be updated including:

* hardhat https://github.com/NomicFoundation/hardhat/pull/4655
* boilerplate https://github.com/NomicFoundation/hardhat-boilerplate/pull/102

## TODO

- [x] Check peer dependencies make sense
- [x] Update sample project tests to better leverage ignition
- [x] Review docs
- [x] #686
- [x] #687
- [x] #688
- [x] #689
- [x] Remove scripts from sample project + update their readmes
- [x] Local manual run of end to end tests with bumped versions
- [x] Run through project setup guide
- [x] Run through boilerplate project
- [x] Review example to work better with Ignition, specifically it is a complicated example that needs lots of Ignition Module features explained.
