### ISSUE TITLE
Provide clean UI when using ledger

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#720]
With the enhancements to `hardhat-ledger` coming from https://github.com/NomicFoundation/hardhat/pull/4946, we can now control the cli UI entirely from Ignition.

## TODO

- [ ] Add `hardhat_setLedgerOutputEnabled` provider rpc call in Ignition deploy to disable ledger cli UI changes
- [ ] Add listeners to the provider that update the UI state
- [ ] Display a waiting for ledger confirmation message at the bottom of the current batch, and update it with successful or failed confirmation
- [ ] Integration test if possible (maybe fake the provider?)

## Potential UI

```shell
Batch #2
  Executed RESOLVER#PublicResolver
  Executed RESOLVER#set_subnode_owner_for_resolver
  Executed REVERSEREGISTRAR#set_subnode_owner_reverse

  Ledger: Connecting wallet
```

```shell
Batch #2
  Executed RESOLVER#PublicResolver
  Executed RESOLVER#set_subnode_owner_for_resolver
  Executed REVERSEREGISTRAR#set_subnode_owner_reverse

  Ledger: Waiting for confirmation
```

```shell
Batch #2
  Executed RESOLVER#PublicResolver
  Executed RESOLVER#set_subnode_owner_for_resolver
  Executed REVERSEREGISTRAR#set_subnode_owner_reverse

  Ledger: Transaction signed
```
