### ISSUE TITLE
Check for anvil in automining check

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#723]
Currently we support automining mode in Hardhat and ganache. Anvil also has an automining mode and its state can be queried with `anvil_getAutomine`.

Anvil docs reference: https://book.getfoundry.sh/reference/anvil/

## TODO

- [ ] Add anvil into the automine check (`packages/core/src/internal/utils/check-automined-network.ts`), based on the `anvil_getAutomine` rpc call
- [ ] Add anvil to the automine check unit tests
- [ ] Consider an integration test (this means getting forge into the CI) - maybe too much

**Comment by zoeyTM** [comment]
Closing this as the `anvil_*` namespace is an alias for `hardhat_*`, therefore our existing check already covers this case.

https://book.getfoundry.sh/reference/anvil/#custom-methods
