### ISSUE TITLE
Report chain id as part of deploy stats

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#751]
To better target our resources we want to understand which chains are seeing the most Ignition deploys. We need to capture that as part of our analytics.

## TODO

- [ ] Confirm this is covered in Hardhat's privacy policy
- [ ] Review GA mechanism for reporting a task invocation and whether we can piggy back on it for tagging the chain id
- [ ] Review whether Sentry transactions are more appropriate

**Comment by kanej** [comment]
We have opted to hold on this until HHv3.
