### ISSUE TITLE
feat: Allow `... ether` to be parsed in parameters

### ISSUE THREAD

**Issue by erhant** [NomicFoundation/hardhat-ignition#790]
### Describe the feature

Since we already have a custom deserializer for parameters (https://github.com/NomicFoundation/hardhat-ignition/issues/663 to parse bigint) i think it makes most sense to also parse w.r.t `parseEther` of ethers, so that instead of writing `"1000000000000000000n"` as parameter which is definitely not human-readable, I could type `1.0 ether`, based on `.endsWith` keyword it can directly parse the value.

In this way, `1.0 gwei` could also be parsed and such.

P.S. would love to work on this!

### Search terms

parameters

**Comment by kanej** [comment]
I suspect we would hesitate before increasing the complexity of the deserialization process. Currently it is JSON.parse with this one additional magic rule for bigints, any additional rules would have to justify the additional complexity.

If this is people see as useful, can I ask you upvote and leave a description of the use case it would help in.

**Comment by erhant** [comment]
thinking of less invasive methods, I was wondering what if we instead allow updating a parameter at runtime, e.g.

```ts
const param = m.getParameter("param-name");
m.setParameter("param-name", param ** 18n); // if param was "10", now its equal to "10 ether"

// allow function argument as well
m.setParameter("param-name", (param) => param ** 18n);
```

**Comment by kanej** [comment]
Hey @erhant, firstly thanks for the suggestions, we have been talking over the approach to take on this internally.

Complexity in the deserializer we try and avoid, but support for arbitrary anonymous functions in the module API makes serializing and deserializing the Module data structures hard - and that is a capability we want to keep.

Some complexity in the deserializer seems like a better tradeoff here, so in effect your first suggested approach.

Let me put together some notes on how to approach adding to the deserializer, I will post them here and we discuss it further if your interested.

**Comment by erhant** [comment]
hey, thanks for letting me know 🙏🏻 

> Let me put together some notes on how to approach adding to the deserializer, I will post them here and we discuss it further if your interested.
I would love that, looking forward!

**Comment by SebastienGllmt** [comment]
I think the better solution to this problem is to instead make the `parameters.json` using JSON5 instead of JSON, as JSON5 is very well supported as a standard, is trivial to turn to native JSON later if needed, and it also allows comments

That is to say, I think if we could something like this
```json5
"MyModule": {
    "endowment": "1000000000000000000n" // 1 ETH in wei
  }
```

That would be great (hey look, even Github supports json5 markdown blocks 🙂)

**Comment by erhant** [comment]
JSON5 makes a lot of sense actually!

**Comment by kanej** [comment]
The approach then would be to use `json5` when parsing the parameters.json file. We would retain the replacer function that converts strings of the "1000n" format to native javascript BigInts.
We won't attempt to leverage JSON5's arbitrary-precision integers to support BigInts.
This will allow users to comment the parameters file to provide context.
We should also check we support the `.json5` extension for parameter files.

## TODO

- [ ] Add `json5` as a dependency: https://www.npmjs.com/package/json5
- [ ] Update the filename checks to support `.json5` as well as `.json`
- [ ] Update the parsing code here, keeping the bigint reviver: https://github.com/NomicFoundation/hardhat-ignition/blob/c4278b68450535781d734ea9fe02a4d654df7a48/packages/hardhat-plugin/src/index.ts#L675
- [ ] Add an integration test with an example project with json5 based parameters file

**Comment by erhant** [comment]
Im taking this on, thanks for the detailed steps!
