### ISSUE TITLE
Enhance transaction list display with etherscan links

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#838]
The transaction list command shows the transaction hash:

![image](https://github.com/user-attachments/assets/27760b99-8dab-49b4-b251-8aa59408eea6)

Is it possible to include a link to etherscan in the output at the cli?

Etherscan has transaction pages, where the url has this form: `https://etherscan.io/tx/0x2707c0aa606ece2fcd6ca9f2de9a56a737104c35d965f13b7f6f36847f5d3abf`

We would want to support different block explorers depending on the chain that was deployed to.

## UI

```
Transaction 1 (🔗 view on Etherscan)
# ...
```

## TODO

- [ ] Determine how we would associate a chain-id in a particular deployment with the correct block explorer url
- [ ] Determine whether we are printing a bare url (i.e. `https://etherscan.io/tx/...`) or whether we can leverage [terminal hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda): https://github.com/Alhadis/OSC8-Adoption
- [ ] Determine the layout for the link
