### ISSUE TITLE
Strategies Support

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat-ignition#91]
> NOTE: this is a placeholder issue for organizing subissues

We want to enable larger projects to extend **Hardhat Ignition** with custom execution logic that we have not thought of, e.g. deploying through a new multisig system.

Our first execution strategy will be `create2`. A user should be able to run a module with the `create2` strategy and have contract deployments proxied through a create2 factory. This should happen seamlessly without the need for modifications to the module. 

### Create2 Support as Internal Strategy

- [x] #206
- [x] https://github.com/NomicFoundation/hardhat-ignition/issues/629
- [x] #661

### Public exposing Strategies in API

- [ ] https://github.com/NomicFoundation/hardhat-ignition/issues/453
- [ ] https://github.com/NomicFoundation/hardhat-ignition/issues/452

**Comment by kanej** [comment]
We have a POC for create2 support. Our plan is to tackle this as:

- get `create2` support out as another internal strategy
- follow on with public strategies api
